### ISSUE TITLE
Custom genesis file for testing

### ISSUE THREAD

**Issue by PawelPodkalicki** [adshares/esc#10]
Start docker with custom genesis file

**Comment by PawelPodkalicki** [comment]
Test with custom genesis:
```
mvn clean test -f pom-esc-qa.xml -Dgenesis.file=PATH_TO_GENESIS_FILE
```

**Comment by michaldzwigala** [comment]
- [x] Adshares/esc/test/load_tests/run/300_genesis.json

- [x] Adshares/esc/test/load_tests/run/900_genesis.json
