### ISSUE TITLE
cannot get broadcast message

### ISSUE THREAD

**Issue by PawelPodkalicki** [adshares/esc#35]
In standard test network (3x3, shortened block time) broadcast message "0102030405" was successfully sent by user 0001-00000000-XXXX, but could not be read. 

After sending message, function _get_broadcast_ was called every 5 seconds for about 2 mins (4 block times). As `from` parameter were used value of "0" and values from _broadcast_ function response - `current_block_time`, `previous_block_time`, `account.time`

Full log is available in __20180517_1742_logs_no_broadcast_msg.zip__ archive.

**Comment by lenter83** [comment]
Try "from" value with a block time in hex format. @PawelPodkalicki
