### ISSUE TITLE
transfer rejected by node

### ISSUE THREAD

**Issue by PawelPodkalicki** [adshares/esc#36]
Standard test network (3x3, shortened block time). Network was left idle for about 15 hours. After that time all three nodes has message `ERROR: no peers, panic` in log.

Runing tests for local and remote tests failed. Every transfer from main account in node1 was rejected - no `tx.id` in _send_one_ nor _send_many_ response.

Full log is available in archive **20180518_0925_logs_transfer_denied.zip**. In directory 20180518_0925_logs are logs before transfer, in 20180518_0933_logs2 are logs after transfer tests.

**Comment by PawelPodkalicki** [comment]
I confirm that computer go to sleep mode during test.

**Comment by lenter83** [comment]
Network is not designed to be put in a sleep
