### ISSUE TITLE
"no peers error" shortly after test network start

### ISSUE THREAD

**Issue by PawelPodkalicki** [adshares/esc#40]
I tried to start test network (32 sec block time) with custom genesis file. Genesis file was prepared for retrieve funds test. genesis file has two accounts in two nodes (2x2). All accounts have same key.

In about 70% attempts shortly after start I get an error:
`ERROR: no peers, panic`
This error signalises that operations between nodes are not available.

Full logs and genesis file are available in **20180521_logs_2nodes_nopeer.zip** archive.
There are 3 logs: two wrong cases and one correct. All were observed with the same genesis file.

**Comment by lenter83** [comment]
Is bug also present in hpx version?

**Comment by PawelPodkalicki** [comment]
Bug didn't occur in hpx.
