### ISSUE TITLE
broadcast function: no message length limit 

### ISSUE THREAD

**Issue by PawelPodkalicki** [adshares/esc#43]
`broadcast` function sends message. There is no information about message length limit.  I suppose that this function should have maximum length of message defined. What kind of data this message should contain and what is the limit of it's size?

**Comment by lenter83** [comment]
Broadcast message length limit was added: 32000 bytes. Please test and update wiki.

**Comment by PawelPodkalicki** [comment]
Test passed.

**Comment by PawelPodkalicki** [comment]
Wiki updated.
